[package]
name = "aoss-curl"
version = "1.0.11"
edition = "2021"
authors = ["Jean Mainguy"]
categories = ["command-line-utilities"]
keywords = ["aws", "opensearch", "sigv4"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/jhandguy/aoss-curl"
documentation = "https://docs.rs/aoss-curl"
description = "Request to Amazon OpenSearch Service with SigV4 🔏"

[lib]
name = "aoss_curl"
path = "src/lib.rs"
doctest = false

[[bin]]
name = "aoss-curl"
test = false
doc = false

[profile.release]
strip = true
lto = true
opt-level = "z"
codegen-units = 1
panic = "abort"

[dependencies]
anyhow = "1.0.79"
async-trait = "0.1.77"
aws-config = "1.1.4"
aws-credential-types = "1.1.2"
aws-mfa = "1.0.11"
aws-sigv4 = { version = "1.1.2", features = ["sigv4a", "http0-compat"] }
aws-smithy-runtime-api = "1.1.2"
hyper = { version = "0.14.28", features = ["full"] }
hyper-rustls = { version = "0.25.0", features = ["webpki-tokio"]}
clap = { version = "4.5.0", features = ["derive", "env"] }
thiserror = "1.0.56"
tokio = { version = "1.36.0", features = ["full"] }

[dev-dependencies]
time = { version = "0.3.34", features = ["formatting"] }
