[package]
name = "aoss-curl"
version = "1.0.7"
edition = "2021"
authors = ["Jean Mainguy"]
categories = ["command-line-utilities"]
keywords = ["aws", "opensearch", "sigv4"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/jhandguy/aoss-curl"
documentation = "https://docs.rs/aoss-curl"
description = "Request to Amazon OpenSearch Service with SigV4 🔏"

[lib]
name = "aoss_curl"
path = "src/lib.rs"
doctest = false

[[bin]]
name = "aoss-curl"
test = false
doc = false

[profile.release]
strip = true
lto = true
opt-level = "z"
codegen-units = 1
panic = "abort"

[dependencies]
anyhow = "1.0.75"
async-trait = "0.1.74"
aws-config = "0.101.0"
aws-credential-types = "0.101.0"
aws-mfa = "1.0.7"
aws-sigv4 = { version = "1.0.0", features = ["sigv4a", "http0-compat"] }
aws-smithy-runtime-api = "0.101.0"
hyper = { version = "0.14.27", features = ["full"] }
hyper-rustls = { version = "0.24.2", features = ["webpki-tokio"]}
clap = { version = "4.4.8", features = ["derive", "env"] }
thiserror = "1.0.50"
tokio = { version = "1.34.0", features = ["full"] }

[dev-dependencies]
time = { version = "0.3.30", features = ["formatting"] }
