[package]
name = "aoss-curl"
version = "0.1.23"
edition = "2021"
authors = ["Jean Mainguy"]
categories = ["command-line-utilities"]
keywords = ["aws", "opensearch", "sigv4"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/jhandguy/aoss-curl"
documentation = "https://docs.rs/aoss-curl"
description = "Request to Amazon OpenSearch Service with SigV4 🔏"

[lib]
name = "aoss_curl"
path = "src/lib.rs"
doctest = false

[[bin]]
name = "aoss-curl"
test = false
doc = false

[dependencies]
anyhow = "1.0.70"
aws-mfa = "0.3.1"
aws-sigv4 = "0.55.1"
hyper = { version = "0.14.26", features = ["full"] }
hyper-rustls = { version = "0.24.0", features = ["webpki-tokio"]}
clap = { version = "4.2.2", features = ["derive", "env"] }
tokio = { version = "1.28.0", features = ["full"] }
