[package]
name = "aoss-curl"
version = "0.1.0"
edition = "2021"
authors = ["Jean Mainguy"]
categories = ["command-line-utilities"]
keywords = ["aws", "opensearch", "sigv4"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/jhandguy/aoss-curl"
description = """
Send HTTP requests signed with SigV4 to Amazon OpenSearch Service 🔏
"""

[lib]
name = "aoss_curl"
path = "src/lib.rs"
doctest = false

[[bin]]
name = "aoss-curl"
test = false
doc = false

[dependencies]
anyhow = "1.0.66"
aws-mfa = "0.2.1"
aws-sigv4 = "0.51.0"
hyper = { version = "0.14", features = ["full"] }
hyper-rustls = { version = "0.23.0", features = ["webpki-tokio"]}
clap = { version = "4.0.18", features = ["derive", "env"] }
tokio = { version = "1.21.2", features = ["full"] }