[package]
name = "aoss-curl"
version = "1.0.13"
edition = "2021"
authors = ["Jean Mainguy"]
categories = ["command-line-utilities"]
keywords = ["aws", "opensearch", "sigv4"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/jhandguy/aoss-curl"
documentation = "https://docs.rs/aoss-curl"
description = "Request to Amazon OpenSearch Service with SigV4 🔏"

[lib]
name = "aoss_curl"
path = "src/lib.rs"
doctest = false

[[bin]]
name = "aoss-curl"
test = false
doc = false

[profile.release]
strip = true
lto = true
opt-level = "z"
codegen-units = 1
panic = "abort"

[dependencies]
anyhow = "1.0.82"
async-trait = "0.1.79"
aws-config = "1.1.8"
aws-credential-types = "1.1.8"
aws-mfa = "1.0.13"
aws-sigv4 = { version = "1.2.0", features = ["sigv4a"] }
aws-smithy-runtime-api = "1.2.0"
clap = { version = "4.5.4", features = ["derive", "env"] }
http-body-util = "0.1.1"
hyper = { version = "1.2.0", features = ["full"] }
hyper-rustls = { version = "0.26.0", features = ["webpki-tokio"]}
hyper-util = { version = "0.1.3", features = ["full"] }
thiserror = "1.0.58"
tokio = { version = "1.37.0", features = ["full"] }

[dev-dependencies]
time = { version = "0.3.35", features = ["formatting"] }
